# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: install anaconda
      - run:
          name: install anaconda
          command: |
            sudo apt update
            sudo apt install -y wget
            cd $HOME
            wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh
            chmod +x ~/miniconda.sh && bash ~/miniconda.sh -b -p $HOME/miniconda
            export PATH=$HOME/miniconda/bin:$PATH
      # Step 3: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            export PATH=$HOME/miniconda/bin:$PATH
            conda env create -f requirements.yml
            conda activate calculator

      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            export PATH=$HOME/miniconda/bin:$PATH
            conda activate calculator
            flake8 --statistics
            pytest -v --cov=calculator
